import type { Metadata } from "next";
import "./globals.css";
import NavMenu from "./NavMenu";
import AuthProvider from "./AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({children}:{children: React.ReactNode}){
  return(
    <html lang="en">
      <body>
        <AuthProvider>
        <div className = "container">
          <NavMenu/>
          <div style={{ flex: 1 }}>{children}</div>
        </div>
        </AuthProvider>
      </body>
    </html>
  );
}
